networks:
  fastapi_network:
    driver: bridge

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_manager_frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001
    networks:
      - fastapi_network
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    container_name: task_manager_db
    environment:
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: task_manager_db
    ports:
      - "5332:5432"
    volumes:
      - task_manager_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_manager_api
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://task_manager:password123@db:5432/task_manager_db
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
    networks:
      - fastapi_network
    stdin_open: true

volumes:
  task_manager_data:
