"""empty message

Revision ID: 178250264463
Revises: cc5a8e43f046
Create Date: 2025-08-25 17:31:37.832913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '178250264463'
down_revision: Union[str, None] = 'cc5a8e43f046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefa', 'data_atualizacao')
    op.drop_column('tarefa', 'data_criacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tarefa', sa.Column('data_atualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
